apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  selector:
    app: zk
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk
spec:
  selector:
    matchLabels:
      app: zk
  replicas: 3
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: Always
        image: "sneyd321/zookeeper"
        ports:
        - containerPort: 2181

      imagePullSecrets:
      - name: key
  
  